SLUG=AudibleInstruments

include ../../../makefile_plugin_pre

EXTRAFLAGS+= -Ieurorack/ -DTEST -Ieurorack/stmlib/third_party/STM -Ieurorack/stmlib/third_party/STM/STM32F0xx_StdPeriph_Driver/inc/

include make.objects

include ../../../makefile_plugin_post
