SLUG=FrozenWasteland

include ../../../makefile_plugin_pre

EXTRAFLAGS+= \
	-DTEST \
	-I./eurorack \
	-I./src/dsp-delay \
	-I./src/dsp-filter/utils -I./src/dsp-filter/filters -I./src/dsp-filter/third-party/falco

include make.objects

include ../../../makefile_plugin_post
